---
abstract: 'pwent and grent support for Win32'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-pwent
provides:
  Win32::pwent:
    file: lib/Win32/pwent.pm
    version: 0.01
requires:
  File::Spec: 0
  Win32: 0
  Win32::NetAdmin: 0.11
  Win32::Registry: 0
  Win32API::Net: 0.13
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
